### ISSUE TITLE
Add Shortcut Option

### ISSUE THREAD

**Issue by ericchase** [ericchase/addon--reload-all-tabs-in-window#2]
An option for configuring a hotkey to run the addon.
Hotkey should be customizable and removable.
Default hotkey should be "None."

**Comment by Caedendi** [comment]
I would also love this option. 

Any chance this could be added in the near-future? Since its already been 2 years since the feature request

**Comment by ericchase** [comment]
> already been 2 years since the feature request

Well, since I'm the one who added the enhancement issue, I never felt the need to add it since I wouldn't use the hotkey.

If you have a use case for it, would you mind explaining it to me?
I predominantly use my mouse when browsing, so clicking the icon is much quicker than say ctrl-shift-r or something.

**Comment by Caedendi** [comment]
theres at least 2 news sites i visit daily where i drag the tab to open in a new window, then select around 20 links to open in new tabs and use the keyboard (ctrl+tab, ctrl+w) to cycle through them. 

it often happens that either darkreader or stylish conflicts or i just feel like switching, or that i accidently wasnt logged in when i clicked the tabs. in that case it would be really convenient to have a single action keyboard hotkey instead of having to move my hand back to the mouse and do another 4 actions.

and yeah i predominantly use the keyboard.

cool extension btw, the only similar one i found would reload all tabs in all windows, which isnt always desirable.

**Comment by ericchase** [comment]
interesting. i'm sure the hotkey code is fairly easy to do. i'll try to add it in when i can

**Comment by ericchase** [comment]
well, this was the easiest addition in my life

**Comment by Caedendi** [comment]
Thanks for adding this. How simple it may be, it is a game changer. Left you a 5-star review.
